# using this for the guide on how to do this - https://github.com/marketplace/actions/deploy-hugo-to-remote
name: huge-remote

on:
  push:
    branches:
      - master

env:
  REMOTE: domacikolaci/adamknezevic-com.git
  DEST: public

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/hugo-build-action@master  # ...or replace 'master' with a full version tag, such as: v0.64.1
      with:
        args: --minify --buildDrafts
    - uses: actions/upload-artifact@master
      with:
        name: website
        path: './public'