baseURL = 'http://adamkenzevic.com/'
languageCode = 'en-us'

[params]
title = "Adam Knezevic"
author = "Adam Knezevic"
description = "IT Security & Project Engineer for large MSP in Australia"
profilePicture = "images/me.jpg"
displayMode = "dark"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/adamknezevic/"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"


copyright = "2020-{{ YEAR }}"
#Reminder - Keep this at bottom always
[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false