baseURL = 'http://adamkenzevic.com/'
languageCode = 'en-us'

[params]
title = "Adam Knezevic"
author = "Adam Knezevic"
description = "IT Security & Project Engineer for large MSP in Australia"
profilePicture = "images/me.jpg"
displayMode = "dark"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/adamknezevic/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/domacikolaci"

[[params.socialIcons]]
icon = "fab fa-git"
title = "GitTea"
url = "https://git.volkor.me/domacikolaci"


[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "blog"
  url = "/blog/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/about/"

copyright = "2020-{{ YEAR }}"
#Reminder - Keep this at bottom always
[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false